# Generated by Django 3.1.1 on 2021-03-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='original',
            field=models.ImageField(upload_to='projects_images', verbose_name='Original'),
        ),
    ]
