# Generated by Django 3.1.1 on 2021-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20210216_1752'),
        ('projects', '0002_auto_20210318_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='about.Skill', verbose_name='Skills'),
        ),
    ]
