# Generated by Django 3.1.1 on 2021-03-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210319_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTag',
        ),
    ]
