version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

  backend:
    build:
      context: .
      dockerfile: docker/BackendDockerfile
    command: /code/docker/start_backend_prod.sh
    volumes:
      - ./backend:/code
      - ./docker:/code/docker
      - ~/.aws:/root/.aws
    ports:
      - "8001:8001"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    command: /code/docker/start_frontend_prod.sh
    volumes:
      - ./frontend:/code
      - ./docker:/code/docker
      - ~/.aws:/root/.aws
    depends_on:
      - backend
