# Generated by Django 3.1.1 on 2020-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Name'), (2, 'Role'), (3, 'Tech Stack')], unique=True)),
                ('text', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Location'), (2, 'LinkedIn'), (3, 'Mail'), (4, 'Telegram')], unique=True)),
                ('text', models.CharField(max_length=64)),
                ('show_in_sidebar', models.BooleanField(default=False)),
                ('show_in_contact', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['type'],
            },
        ),
    ]
