# Generated by Django 3.1.1 on 2020-09-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='show_in_contact',
            field=models.BooleanField(default=False, verbose_name='Show in Contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='show_in_sidebar',
            field=models.BooleanField(default=False, verbose_name='Show in Sidebar'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(max_length=64, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Location'), (2, 'LinkedIn'), (3, 'Mail'), (4, 'Telegram')], unique=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='url',
            field=models.CharField(blank=True, max_length=64, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='title',
            name='text',
            field=models.CharField(max_length=64, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='title',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Name'), (2, 'Role'), (3, 'Tech Stack')], unique=True, verbose_name='Type'),
        ),
    ]
