# Generated by Django 3.1.1 on 2021-03-18 12:42

import apps.core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactmeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='photo', verbose_name='Original')),
            ],
            bases=(apps.core.mixins.SingleModelMixin, models.Model),
        ),
    ]
