# Generated by Django 3.1.1 on 2021-02-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_timeline_timelineentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='about.timeline', verbose_name='Timeline'),
        ),
    ]
