name: DEPLOY OT EC2

on:
  push:
    branches:
      - master

jobs:
  ec2-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.EC2_USER }}
          SSH_KEY: ${{ secrets.EC2_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
      - name: Upload the code to ec2 and restart docker
        run: ssh prod 'cd apps/portfolio/ && git pull && docker-compose -f docker-compose-prod.yaml restart'
