name: UPLOAD TO S3

on:
  push:
    branches:
      - actions

jobs:
  s3-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: cd frontend
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build
      - name: Uploading to s3
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
